name: Deploy MkDocs
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Action (deploy by default)'
        required: false
        default: 'deploy'
        type: choice
        options:
          - build-only
          - deploy

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build or Deploy
        shell: powershell
        run: |
          # 极简模式：移除所有非必需字符
          if (${{ github.event.inputs.environment }} -eq "build-only") {
            mkdocs build
            echo "Build success"
          } else {
            mkdocs gh-deploy --force
            echo "Deploy success"
          }
