name: Deploy MkDocs
on:
  # 触发条件：推送到 main 分支 或 手动触发
  push:
    branches: [main]
  workflow_dispatch:  # 允许手动运行工作流
    inputs:
      environment:
        description: '选择操作（默认部署）'
        required: false
        default: 'deploy'
        type: choice
        options:
          - build-only
          - deploy

jobs:
  deploy:
    runs-on: windows-latest  # 改为 Windows 环境
    steps:
      # 步骤1：拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2：设置 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # 明确指定版本（Windows 推荐）

      # 步骤3：安装 MkDocs（Windows 可能需要调整路径）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # 步骤4：根据手动输入选择操作
      - name: Build or Deploy
        run: |
          if ("${{ github.event.inputs.environment }}" == "build-only") {
            mkdocs build
            echo "仅构建，不部署"
          } else {
            mkdocs gh-deploy --force
            echo "已部署到 GitHub Pages"
          }
        shell: bash  # 在 Windows 中使用 bash 执行（需 Git Bash）
