name: Deploy MkDocs
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: '选择操作（默认部署）'
        required: false
        default: 'deploy'
        type: choice
        options:
          - build-only
          - deploy

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build or Deploy
        shell: powershell
        run: |
          $env:PYTHONIOENCODING = "utf-8"
          if ("${{ github.event.inputs.environment }}" -eq "build-only") {
            mkdocs build
            Write-Output "构建完成"
          } else {
            mkdocs gh-deploy --force
            Write-Output "已部署到 GitHub Pages"
          }
